---
- name: Install Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install nginx package
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Restore default nginx page
      copy:
        src: /usr/share/nginx/html/index.html
        dest: /var/www/html/index.nginx-debian.html
        remote_src: yes
    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: true
