---
- name: Create multiple users
  hosts: all
  become: yes
  tasks:
    - name: Add users
      user:
        name: "{{ item }}"
        state: absent
        shell: /bin/bash
      loop:
        - dev1
        - dev2
        - dev3
